//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traunappwindow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string OrderName { get; set; }
        public double P { get; set; }
        public double S { get; set; }
        public int Spotlight { get; set; }
        public int Lustra { get; set; }
        public int Pipe { get; set; }
        public int Ugl { get; set; }
        public int ClientId { get; set; }
    
        public virtual Clients Client { get; set; }
    }
}
